spring:
  application:
    name: frontend
  sleuth:
    trace-id128: true
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://develop:9411
server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
